// <auto-generated />
using System;
using AlarmMonitor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlarmMonitor.Migrations
{
    [DbContext(typeof(AlarmContext))]
    [Migration("20260108125924_AddTagMaster")]
    partial class AddTagMaster
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlarmMonitor.Models.AlarmEvent", b =>
                {
                    b.Property<Guid>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Acked")
                        .HasColumnType("bit");

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("AlarmClass")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("AutoUnshelveTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ChangeMask")
                        .HasColumnType("int");

                    b.Property<string>("ComputerID")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ConditionName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Disabled")
                        .HasColumnType("bit");

                    b.Property<bool?>("EffDisabled")
                        .HasColumnType("bit");

                    b.Property<bool?>("EffSuppressed")
                        .HasColumnType("bit");

                    b.Property<Guid?>("EventAssociationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventCategory")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("EventTimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EventType")
                        .HasColumnType("int");

                    b.Property<string>("GroupPath")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<double?>("InputValue")
                        .HasColumnType("float");

                    b.Property<double?>("LimitValue")
                        .HasColumnType("float");

                    b.Property<string>("Message")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid?>("MessageID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PersonID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("Quality")
                        .HasColumnType("int");

                    b.Property<string>("ServerName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Severity")
                        .HasColumnType("int");

                    b.Property<Guid?>("SourceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourcePath")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("SubConditionName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Suppressed")
                        .HasColumnType("bit");

                    b.Property<string>("Tag1Value")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Tag2Value")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Tag3Value")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Tag4Value")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("TicksTimeStamp")
                        .HasColumnType("bigint");

                    b.Property<string>("UserComment")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("EventID");

                    b.ToTable("AlarmEvents");
                });

            modelBuilder.Entity("AlarmMonitor.Models.TagMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<float>("HighLimit")
                        .HasColumnType("real");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<float>("LowLimit")
                        .HasColumnType("real");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TagMasters");
                });
#pragma warning restore 612, 618
        }
    }
}
